#!/bin/bash

CHANGELOG=CHANGELOG.md
CONTRIBUTORS=CONTRIBUTORS.md

echo > $CHANGELOG
unset LAST_TAG
for TAG in $(git tag | tac); do
  if [[ -v LAST_TAG ]]; then
    git log $TAG..$LAST_TAG --oneline | sed 's/^/* /' >> $CHANGELOG
  fi
  echo "## $TAG" >> $CHANGELOG
  LAST_TAG=$TAG
done
git log $LAST_TAG --oneline | sed 's/^/* /' >> $CHANGELOG

git shortlog -n -s | cut -f2 | sed 's/^/* /' > CONTRIBUTORS.md
