import {
  anyAsync,
  appendAsync,
  avgAsync,
  merge,
  mergeCatching,
  prependAsync,
  forEachAsync,
  groupAsync,
  joinAsync,
  partitionAsync,
  takeWhileAsync,
  distinctAsync,
  executeAsync,
  filterAsync,
  firstAsync,
  flattenAsync,
  mapAsync,
  skipWhileAsync,
  toObjectAsync,
  allAsync,
  reduceAndMapAsync,
  lastAsync,
  repeatAsync,
  skipAsync,
  sortAsync,
  toArrayAsync,
  takeAsync,
  withIndexAsync,
  concatAsync,
  hasExactlyAsync,
  hasLessThanAsync,
  hasMoreThanAsync,
} from './async';
import {} from './async/first-async';
import { countAsync } from './async/count-async';
import { reduceAsync } from './async/reduce-async';
import { topAsync } from './async/top-async';
import { minAsync } from './async/min-async';
import { maxAsync } from './async/max-async';
import { sumAsync } from './async/sum-async';
import { containsAsync } from './async/contains-async';

export const asyncHelper = {
  withIndex: withIndexAsync,
  takeWhile: takeWhileAsync,
  take: takeAsync,
  skipWhile: skipWhileAsync,
  skip: skipAsync,
  map: mapAsync,
  filter: filterAsync,
  partition: partitionAsync,
  append: appendAsync,
  prepend: prependAsync,
  concat: concatAsync,
  repeat: repeatAsync,
  flatten: flattenAsync,
  sort: sortAsync,
  distinct: distinctAsync,
  count: countAsync,
  first: firstAsync,
  last: lastAsync,
  reduceAndMap: reduceAndMapAsync,
  reduce: reduceAsync,
  all: allAsync,
  any: anyAsync,
  contains: containsAsync,
  toArray: toArrayAsync,
  toObject: toObjectAsync,
  forEach: forEachAsync,
  execute: executeAsync,
  join: joinAsync,
  sum: sumAsync,
  avg: avgAsync,
  top: topAsync,
  min: minAsync,
  max: maxAsync,
  hasExactly: hasExactlyAsync,
  hasLessThan: hasLessThanAsync,
  hasMoreThan: hasMoreThanAsync,
  merge,
};

export const asyncIterableFuncs = {
  withIndex: withIndexAsync,
  takeWhile: takeWhileAsync,
  takeWhileAsync,
  take: takeAsync,
  skipWhile: skipWhileAsync,
  skipWhileAsync,
  skip: skipAsync,
  map: mapAsync,
  mapAsync,
  filter: filterAsync,
  filterAsync,
  append: appendAsync,
  prepend: prependAsync,
  concat: concatAsync,
  repeat: repeatAsync,
  flatten: flattenAsync,
  flattenAsync,
  sort: sortAsync,
  distinct: distinctAsync,
  distinctAsync,
  group: groupAsync,
  groupAsync,
  execute: executeAsync,
  executeAsync,
  merge,
  mergeCatching,
};

export const asyncSpecial = {
  partition: partitionAsync,
  group: groupAsync,
  groupAsync,
};

export const asyncResolvingFuncs = {
  count: countAsync,
  countAsync,
  first: firstAsync,
  firstAsync,
  last: lastAsync,
  lastAsync,
  reduceAndMap: reduceAndMapAsync,
  reduceAndMapAsync,
  reduce: reduceAsync,
  reduceAsync,
  all: allAsync,
  allAsync,
  any: anyAsync,
  anyAsync,
  contains: containsAsync,
  containsAsync,
  toArray: toArrayAsync,
  toObject: toObjectAsync,
  toObjectAsync,
  forEach: forEachAsync,
  forEachAsync,
  join: joinAsync,
  joinAsync,
  sum: sumAsync,
  sumAsync,
  avg: avgAsync,
  avgAsync,
  top: topAsync,
  topAsync,
  min: minAsync,
  minAsync,
  max: maxAsync,
  maxAsync,
  hasExactly: hasExactlyAsync,
  hasLessThan: hasLessThanAsync,
  hasMoreThan: hasMoreThanAsync,
};
