name: benchmark

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [26.x, 24.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Benchmark augmentative-iterable
        run: pnpm --filter augmentative-iterable test:benchmark
      - name: Benchmark fluent-iterable
        run: pnpm --filter @codibre/fluent-iterable test:benchmark
